/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package package_1;

import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class Customer_Form extends javax.swing.JFrame {
int count=0;
    /**
     * Creates new form Customer_Form
     */
    public Customer_Form() {
        initComponents();
        setSize(890,740);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_1 = new javax.swing.JTextField();
        txt_2 = new javax.swing.JTextField();
        txt_4 = new javax.swing.JTextField();
        box_1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        txt_5 = new javax.swing.JPasswordField();
        txt_3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel2.setText("Create your Account.It's free and only take a minute");

        txt_1.setText("First Name");
        txt_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_1MousePressed(evt);
            }
        });
        txt_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_1ActionPerformed(evt);
            }
        });

        txt_2.setText("Last Name");
        txt_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_2MouseClicked(evt);
            }
        });

        txt_4.setText("Email");
        txt_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_4MouseClicked(evt);
            }
        });

        box_1.setText("I acccepts the term of Use and Privacy Policy.");
        box_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 102, 0));
        jButton1.setText("Register Now");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txt_5.setText("jPasswordField1");
        txt_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_5MouseClicked(evt);
            }
        });

        txt_3.setText("Mobile Number");
        txt_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_3MouseClicked(evt);
            }
        });
        txt_3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_3KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(txt_1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(51, 51, 51)
                            .addComponent(txt_2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txt_4)
                    .addComponent(box_1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_5)
                    .addComponent(txt_3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(txt_3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(txt_4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(txt_5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(box_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(24, 24, 24))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(194, 193, 473, 430);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel1.setBackground(new java.awt.Color(0, 102, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("                REGISTER");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(54, 37, 776, 138);

        jPanel3.setBackground(new java.awt.Color(102, 153, 0));

        jButton2.setText("Sign in");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(465, 630, 95, 51);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Already have an Account ?");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(260, 650, 190, 16);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/package_1/stock-vector-hipster-modern-geometric-abstract-background-bright-yellow-banner-with-blue-stripes-stripes-724350736.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 10, 2300, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        super.dispose();
        new Login_Form().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(box_1.isSelected()){
        String first,last,email,pass,mobile;
        first=txt_1.getText();
         last=txt_2.getText();
       mobile=txt_3.getText();
        email=txt_4.getText();
         pass=String.valueOf(txt_5.getPassword());
         if(first.equals("First Name")){
             JOptionPane.showMessageDialog(this,"Enter the details properly");
             return;
         }
         if (last.equals("Last Name")){
             JOptionPane.showMessageDialog(this,"Enter the details properly");
             return;
            }
         if(email.equals("Email")){
             JOptionPane.showMessageDialog(this,"Enter the details properly");
             return;
         }
         
        try {
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql:///help_helper","root","");
            if(con!=null){
                String check="Select * from customer_data where Email=?";
                PreparedStatement ps1=con.prepareStatement(check);
                ps1.setString(1,email);
                ResultSet rs=ps1.executeQuery();
                if(rs.next()){
                    JOptionPane.showMessageDialog(this,"This Email_Id already exist ");
                }
                else{
                String query="insert into customer_data(First_name,Last_name,Mobile,Email,Password) values(?,?,?,?,?)";
                PreparedStatement ps=con.prepareStatement(query);
                ps.setString(1,first);
                ps.setString(2,last);
                ps.setString(3,mobile);
                ps.setString(4,email);
                ps.setString(5,pass);
                int row=ps.executeUpdate();
                if(row>0)
                {
                    String str="Select MAX(Customer_id) from customer_data";
                     ps1=con.prepareStatement(str);
                     rs=ps1.executeQuery();
                    if(rs.next())
                    {
                        int a=rs.getInt(1);
                        JOptionPane.showMessageDialog(this,"Your Customer_Id is "+a+" . Remember it for future Reference ." );
                        super.dispose();
                        new Customer_Complaints(a).setVisible(true);
                    }
                    
                }
              }
            }else
            {
                System.out.println("Connection Not Estabilished");
            }
            
        }
        catch(Exception ex){
            System.out.println(ex.toString());
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_3KeyTyped
        if(Character.isDigit(evt.getKeyChar()))
        {
            if(count>=10)
            {
                JOptionPane.showMessageDialog(this,"MAXIMUM LIMIT REACHED");
                evt.consume();
            }
            count=count+1;
        }
        else
        {
            
            evt.consume();
        }
    }//GEN-LAST:event_txt_3KeyTyped

    private void box_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box_1ActionPerformed

    private void txt_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_1MouseClicked
        
    }//GEN-LAST:event_txt_1MouseClicked

    private void txt_1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_1MousePressed
        txt_1.setText(null);

    }//GEN-LAST:event_txt_1MousePressed

    private void txt_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_1ActionPerformed
    
    }//GEN-LAST:event_txt_1ActionPerformed

    private void txt_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_2MouseClicked
        txt_2.setText(null);

    }//GEN-LAST:event_txt_2MouseClicked

    private void txt_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_3MouseClicked
        txt_3.setText(null);

    }//GEN-LAST:event_txt_3MouseClicked

    private void txt_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_4MouseClicked
        txt_4.setText(null);

    }//GEN-LAST:event_txt_4MouseClicked

    private void txt_5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_5MouseClicked
        txt_5.setText(null);

    }//GEN-LAST:event_txt_5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox box_1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txt_1;
    private javax.swing.JTextField txt_2;
    private javax.swing.JTextField txt_3;
    private javax.swing.JTextField txt_4;
    private javax.swing.JPasswordField txt_5;
    // End of variables declaration//GEN-END:variables
}
